swagger: '2.0'
info:
  version: 1.0.0
  title: Сервиc автопроката
basePath: /
tags:
  - name: Методы
schemes:
  - http
paths:
  '/client':
    post:
      tags:
          - Клиенты
      summary: Добавление клиента
      description: 'Добавление клиента'
      operationId: addNewClient
      consumes:
        - application/json;charset=utf-8
      produces:
        - application/json;charset=utf-8
      parameters:
        - name: newClient
          in: body
          description: Новый клиент
          required: true
          schema:
            $ref: '#/definitions/NewClient'
      responses:
        '200':
          description: Успешно
          schema:
            type: array
            items:
              type: object
              $ref: '#/definitions/Client'
  '/clientList':
    get:
      tags:
        - Клиенты
      summary: Получение списка клиентов
      description: 'Получение списка клиентов'
      operationId: getClientList
      produces:
        - application/json;charset=utf-8
      parameters: []
      responses:
        '200':
          description: Успешно
          schema:
            type: array
            items:
              type: object
              $ref: '#/definitions/Client'
definitions:
  Client:
    type: object
    properties:
      id:
        type: number
        description: Ид клиента
      name:
        type: string
        description: Имя клиента
  NewClient:
    type: object
    properties:
      name:
        type: string
        description: Имя клиента
      birthYear:
        type: number
        description: Год рождения клиента
      email:
        type: string
        description: Email клиента

